/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthorityRouteImport } from './routes/authority'
import { Route as CitizenRouteImport } from './routes/citizen'
import { Route as AuthorityIndexRouteImport } from './routes/authority.index'
import { Route as AuthorityComplaintsRouteImport } from './routes/authority.complaints'
import { Route as AuthorityMapRouteImport } from './routes/authority.map'
import { Route as AuthorityPredictionsRouteImport } from './routes/authority.predictions'
import { Route as AuthorityReportsRouteImport } from './routes/authority.reports'
import { Route as AuthorityRiskRouteImport } from './routes/authority.risk'
import { Route as AuthoritySettingsRouteImport } from './routes/authority.settings'
import { Route as LoginAuthorityRouteImport } from './routes/login.authority'
import { Route as LoginCitizenRouteImport } from './routes/login.citizen'
import { Route as AuthorityInfrastructureIndexRouteImport } from './routes/authority.infrastructure.index'
import { Route as AuthorityInfrastructureAssetIdRouteImport } from './routes/authority.infrastructure.$assetId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorityRoute = AuthorityRouteImport.update({
  id: '/authority',
  path: '/authority',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenRoute = CitizenRouteImport.update({
  id: '/citizen',
  path: '/citizen',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorityIndexRoute = AuthorityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthorityRoute,
} as any)
const AuthorityComplaintsRoute = AuthorityComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => AuthorityRoute,
} as any)
const AuthorityMapRoute = AuthorityMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthorityRoute,
} as any)
const AuthorityPredictionsRoute = AuthorityPredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => AuthorityRoute,
} as any)
const AuthorityReportsRoute = AuthorityReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthorityRoute,
} as any)
const AuthorityRiskRoute = AuthorityRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AuthorityRoute,
} as any)
const AuthoritySettingsRoute = AuthoritySettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthorityRoute,
} as any)
const LoginAuthorityRoute = LoginAuthorityRouteImport.update({
  id: '/login/authority',
  path: '/login/authority',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginCitizenRoute = LoginCitizenRouteImport.update({
  id: '/login/citizen',
  path: '/login/citizen',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorityInfrastructureIndexRoute =
  AuthorityInfrastructureIndexRouteImport.update({
    id: '/infrastructure/',
    path: '/infrastructure/',
    getParentRoute: () => AuthorityRoute,
  } as any)
const AuthorityInfrastructureAssetIdRoute =
  AuthorityInfrastructureAssetIdRouteImport.update({
    id: '/infrastructure/$assetId',
    path: '/infrastructure/$assetId',
    getParentRoute: () => AuthorityRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authority': typeof AuthorityRouteWithChildren
  '/citizen': typeof CitizenRoute
  '/authority/complaints': typeof AuthorityComplaintsRoute
  '/authority/map': typeof AuthorityMapRoute
  '/authority/predictions': typeof AuthorityPredictionsRoute
  '/authority/reports': typeof AuthorityReportsRoute
  '/authority/risk': typeof AuthorityRiskRoute
  '/authority/settings': typeof AuthoritySettingsRoute
  '/login/authority': typeof LoginAuthorityRoute
  '/login/citizen': typeof LoginCitizenRoute
  '/authority/': typeof AuthorityIndexRoute
  '/authority/infrastructure/$assetId': typeof AuthorityInfrastructureAssetIdRoute
  '/authority/infrastructure/': typeof AuthorityInfrastructureIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/citizen': typeof CitizenRoute
  '/authority/complaints': typeof AuthorityComplaintsRoute
  '/authority/map': typeof AuthorityMapRoute
  '/authority/predictions': typeof AuthorityPredictionsRoute
  '/authority/reports': typeof AuthorityReportsRoute
  '/authority/risk': typeof AuthorityRiskRoute
  '/authority/settings': typeof AuthoritySettingsRoute
  '/login/authority': typeof LoginAuthorityRoute
  '/login/citizen': typeof LoginCitizenRoute
  '/authority': typeof AuthorityIndexRoute
  '/authority/infrastructure/$assetId': typeof AuthorityInfrastructureAssetIdRoute
  '/authority/infrastructure': typeof AuthorityInfrastructureIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/authority': typeof AuthorityRouteWithChildren
  '/citizen': typeof CitizenRoute
  '/authority/complaints': typeof AuthorityComplaintsRoute
  '/authority/map': typeof AuthorityMapRoute
  '/authority/predictions': typeof AuthorityPredictionsRoute
  '/authority/reports': typeof AuthorityReportsRoute
  '/authority/risk': typeof AuthorityRiskRoute
  '/authority/settings': typeof AuthoritySettingsRoute
  '/login/authority': typeof LoginAuthorityRoute
  '/login/citizen': typeof LoginCitizenRoute
  '/authority/': typeof AuthorityIndexRoute
  '/authority/infrastructure/$assetId': typeof AuthorityInfrastructureAssetIdRoute
  '/authority/infrastructure/': typeof AuthorityInfrastructureIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authority'
    | '/citizen'
    | '/authority/complaints'
    | '/authority/map'
    | '/authority/predictions'
    | '/authority/reports'
    | '/authority/risk'
    | '/authority/settings'
    | '/login/authority'
    | '/login/citizen'
    | '/authority/'
    | '/authority/infrastructure/$assetId'
    | '/authority/infrastructure/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/citizen'
    | '/authority/complaints'
    | '/authority/map'
    | '/authority/predictions'
    | '/authority/reports'
    | '/authority/risk'
    | '/authority/settings'
    | '/login/authority'
    | '/login/citizen'
    | '/authority'
    | '/authority/infrastructure/$assetId'
    | '/authority/infrastructure'
  id:
    | '__root__'
    | '/'
    | '/authority'
    | '/citizen'
    | '/authority/complaints'
    | '/authority/map'
    | '/authority/predictions'
    | '/authority/reports'
    | '/authority/risk'
    | '/authority/settings'
    | '/login/authority'
    | '/login/citizen'
    | '/authority/'
    | '/authority/infrastructure/$assetId'
    | '/authority/infrastructure/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthorityRoute: typeof AuthorityRouteWithChildren
  CitizenRoute: typeof CitizenRoute
  LoginAuthorityRoute: typeof LoginAuthorityRoute
  LoginCitizenRoute: typeof LoginCitizenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authority': {
      id: '/authority'
      path: '/authority'
      fullPath: '/authority'
      preLoaderRoute: typeof AuthorityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen': {
      id: '/citizen'
      path: '/citizen'
      fullPath: '/citizen'
      preLoaderRoute: typeof CitizenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authority/': {
      id: '/authority/'
      path: '/'
      fullPath: '/authority/'
      preLoaderRoute: typeof AuthorityIndexRouteImport
      parentRoute: typeof AuthorityRoute
    }
    '/authority/complaints': {
      id: '/authority/complaints'
      path: '/complaints'
      fullPath: '/authority/complaints'
      preLoaderRoute: typeof AuthorityComplaintsRouteImport
      parentRoute: typeof AuthorityRoute
    }
    '/authority/map': {
      id: '/authority/map'
      path: '/map'
      fullPath: '/authority/map'
      preLoaderRoute: typeof AuthorityMapRouteImport
      parentRoute: typeof AuthorityRoute
    }
    '/authority/predictions': {
      id: '/authority/predictions'
      path: '/predictions'
      fullPath: '/authority/predictions'
      preLoaderRoute: typeof AuthorityPredictionsRouteImport
      parentRoute: typeof AuthorityRoute
    }
    '/authority/reports': {
      id: '/authority/reports'
      path: '/reports'
      fullPath: '/authority/reports'
      preLoaderRoute: typeof AuthorityReportsRouteImport
      parentRoute: typeof AuthorityRoute
    }
    '/authority/risk': {
      id: '/authority/risk'
      path: '/risk'
      fullPath: '/authority/risk'
      preLoaderRoute: typeof AuthorityRiskRouteImport
      parentRoute: typeof AuthorityRoute
    }
    '/authority/settings': {
      id: '/authority/settings'
      path: '/settings'
      fullPath: '/authority/settings'
      preLoaderRoute: typeof AuthoritySettingsRouteImport
      parentRoute: typeof AuthorityRoute
    }
    '/login/authority': {
      id: '/login/authority'
      path: '/login/authority'
      fullPath: '/login/authority'
      preLoaderRoute: typeof LoginAuthorityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/citizen': {
      id: '/login/citizen'
      path: '/login/citizen'
      fullPath: '/login/citizen'
      preLoaderRoute: typeof LoginCitizenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authority/infrastructure/': {
      id: '/authority/infrastructure/'
      path: '/infrastructure'
      fullPath: '/authority/infrastructure/'
      preLoaderRoute: typeof AuthorityInfrastructureIndexRouteImport
      parentRoute: typeof AuthorityRoute
    }
    '/authority/infrastructure/$assetId': {
      id: '/authority/infrastructure/$assetId'
      path: '/infrastructure/$assetId'
      fullPath: '/authority/infrastructure/$assetId'
      preLoaderRoute: typeof AuthorityInfrastructureAssetIdRouteImport
      parentRoute: typeof AuthorityRoute
    }
  }
}

interface AuthorityRouteChildren {
  AuthorityComplaintsRoute: typeof AuthorityComplaintsRoute
  AuthorityMapRoute: typeof AuthorityMapRoute
  AuthorityPredictionsRoute: typeof AuthorityPredictionsRoute
  AuthorityReportsRoute: typeof AuthorityReportsRoute
  AuthorityRiskRoute: typeof AuthorityRiskRoute
  AuthoritySettingsRoute: typeof AuthoritySettingsRoute
  AuthorityIndexRoute: typeof AuthorityIndexRoute
  AuthorityInfrastructureAssetIdRoute: typeof AuthorityInfrastructureAssetIdRoute
  AuthorityInfrastructureIndexRoute: typeof AuthorityInfrastructureIndexRoute
}

const AuthorityRouteChildren: AuthorityRouteChildren = {
  AuthorityComplaintsRoute: AuthorityComplaintsRoute,
  AuthorityMapRoute: AuthorityMapRoute,
  AuthorityPredictionsRoute: AuthorityPredictionsRoute,
  AuthorityReportsRoute: AuthorityReportsRoute,
  AuthorityRiskRoute: AuthorityRiskRoute,
  AuthoritySettingsRoute: AuthoritySettingsRoute,
  AuthorityIndexRoute: AuthorityIndexRoute,
  AuthorityInfrastructureAssetIdRoute: AuthorityInfrastructureAssetIdRoute,
  AuthorityInfrastructureIndexRoute: AuthorityInfrastructureIndexRoute,
}

const AuthorityRouteWithChildren = AuthorityRoute._addFileChildren(
  AuthorityRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthorityRoute: AuthorityRouteWithChildren,
  CitizenRoute: CitizenRoute,
  LoginAuthorityRoute: LoginAuthorityRoute,
  LoginCitizenRoute: LoginCitizenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
